package com.achersoft.tdcc.enums;

public enum DamageModEffect {
    NO_DAMAGE_MOD, MISFIRE, TRIPPLE_CRIT_ON_20, TRIPPLE_CRIT_ON_FIRST_20, TRIPPLE_CRIT, ALWAYS_CRIT, PLUS_2_SNEAK_DAMAGE,
    DAZE_19, DAZE_20, STUN_19, STUN_20, FURRY_THROW
}