package com.achersoft.tdcc.enums;

public enum MonsterEffects {
    PHASING_NORMAL,
    PHASING_HARDCORE,
    PHASING_NIGHTMARE,
    MELEE_MAIN_ON_20,
    MELEE_OFFHAND_ON_20,
    RANGE_MAIN_ON_20,
    RANGE_OFFHAND_ON_20,
    PHASING_EPIC,
    COLD_PIERCE,
    COLD_RESIST_50,
    INCORPOREAL,
    SUBDUE,
    SHOCK_HEAL,
    MISS_50,
    FIRE_HEAL;
}