package com.achersoft.tdcc.enums;

public enum Stat {
    STR, DEX, CON, INTEL, WIS, CHA, HEALTH, REGEN, MELEE_HIT, MELEE_DMG, MELEE_POLY_HIT, MELEE_POLY_DMG, BENROW_HIT, BENROW_DMG,
    MELEE_FIRE, MELEE_COLD, MELEE_SHOCK, MELEE_SONIC, MELEE_ELDRICH, MELEE_POISON, MELEE_DARKRIFT, MELEE_SACRED,
    MELEE_AC, RANGE_HIT, RANGE_DMG, RANGE_FIRE, RANGE_COLD, RANGE_SHOCK, RANGE_SONIC, RANGE_ELDRICH, RANGE_POISON,
    RANGE_DARKRIFT, RANGE_SACRED, RANGE_AC, RANGE_MISSILE_AC, FORT, REFLEX, WILL, RET_DMG, RET_FIRE, RET_COLD,
    RET_SHOCK, RET_SONIC, RET_ELDRICH, RET_POISON, RET_DARKRIFT, RET_SACRED, CANNOT_BE_SUPRISED, FREE_MOVEMENT,
    SPELL_DMG, SPELL_HEAL, SPELL_RESIST, INITIATIVE, DR_MELEE, DR_RANGE, DR_SPELL, DR_FIRE, DR_COLD, DR_SHOCK,
    DR_SONIC, DR_ELDRICH, DR_POISON, DR_DARKRIFT, DR_SACRED, DR_FORCE, DR_ACID, CONSTRUCT_IMMUNITY, PERCENT_HEALTH;
}


