package com.achersoft.tdcc.token.admin.dao;

import com.achersoft.tdcc.enums.ConditionalUse;
import com.achersoft.tdcc.enums.Rarity;
import com.achersoft.tdcc.enums.Slot;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Builder
@Data
@NoArgsConstructor 
@AllArgsConstructor
public class TokenFullDetails {
    private String id;
    private String name;
    private String text;
    private Rarity rarity;
    private Slot slot;
    private boolean usableByBarbarian;
    private boolean usableByBard;
    private boolean usableByCleric;
    private boolean usableByDruid;
    private boolean usableByFighter;
    private boolean usableByWizard;
    private boolean usableByMonk;
    private boolean usableByPaladin;
    private boolean usableByRanger;
    private boolean usableByRogue;
    private Integer str;
    private Integer dex;
    private Integer con;
    private Integer intel;
    private Integer wis;
    private Integer cha;
    private Integer health;
    private Boolean oneHanded;
    private Boolean twoHanded;
    private Boolean shield;
    private Boolean thrown;
    private Boolean rangerOffhand;
    private Boolean instrument;
    private Integer meleeHit;
    private Integer meleeDmg;
    private Boolean meleeFire;
    private Boolean meleeCold;
    private Boolean meleeShock;
    private Boolean meleeSonic;
    private Boolean meleeEldritch;
    private Boolean meleePoison;
    private Boolean meleeDarkrift;
    private Boolean meleeSacred;
    private Integer meleeAC;
    private Boolean rangedWeapon;
    private Integer rangeHit;
    private Integer rangeDmg;
    private Boolean rangeFire;
    private Boolean rangeCold;
    private Boolean rangeShock;
    private Boolean rangeSonic;
    private Boolean rangeEldritch;
    private Boolean rangePoison;
    private Boolean rangeDarkrift;
    private Boolean rangeSacred;
    private Integer rangeAC;
    private Integer rangeMissileAC;
    private Integer fort;
    private Integer reflex;
    private Integer will;
    private Integer retDmg;
    private Boolean retFire;
    private Boolean retCold;
    private Boolean retShock;
    private Boolean retSonic;
    private Boolean retEldritch;
    private Boolean retPoison;
    private Boolean retDarkrift;
    private Boolean retSacred;
    private Boolean cannotBeSuprised;
    private Boolean freeMovement;
    private Boolean psychic;
    private Integer spellDmg;
    private Integer spellHeal;
    private Integer spellResist;
    private Integer initiative;  
    private Integer treasure;  
    private ConditionalUse conditionalUse;
    private Boolean alwaysInEffect;
    private Boolean oncePerRound;
    private Boolean oncePerRoom;
    private Boolean oncePerGame;
    private String specialText;
}
